### ISSUE TITLE
API Documentation - master branch link is broken.

### ISSUE THREAD

**Issue by a-jamesregan** [maidsafe/safe_client#124]
The API Documentation link doesn't seem to work...  Right now it points to http://maidsafe.net/safe_client/master.

**Comment by krishnaIndia** [comment]
Issue has been resolved. We recently renamed the repository from `maidsafe_client` to `safe_client`. The documentation in the master will be using the old name till the master branch builds successful.

Thanks @a-jamesregan for reporting the issue.
