### ISSUE TITLE
cargo test hanging

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_client#155]
Most days I run a script to build and test all the maidsafe Rust repos. This has worked for a few weeks without hangs. As part of these scripts a test.sh bash script (included at the end) is run (after getting latest Rust nightly, removing the repos, doing a new git clone and then cargo build). 

For about ten days the test script has hung during safe_client "cargo test" after displaying test::account_creation. Ctrl-C and then manual "cargo test" completed the test ok so I just left it. Now it is still hanging during the script, but doing the manual cargo test also hung just now, but at "test structured_data_operations::test::data_can_fit_in_structured_data ... ok"

That seems very odd. I've not had any of the other repos hanging like this, but as you can see from the script below, only accumulator, crust and drive are done before safe_client, so I wouldn't see the subsequent ones do so. 

```
 #!/bin/bash

echo "===================================================================="
echo "========================== test.sh ================================="
# Disable multi-threading for crust tests:
export RUST_TEST_THREADS=1

for f in accumulator  crust  drive  safe_client  safe_vault  safe_nfs routing  self_encryption sentinel  
    do
        echo "====== test $f ======"
        cd $f
        cargo test
        cd ..
    done
```

Note: this is on debian Jesse.

**Comment by theWebalyst** [comment]
Update: I tried moving safe_client to the end of the "for r" line in the script (see first comment) and it appears to have hung in safe_vault at the second test ("test executable_immutable_data_churn_test"). So this appears to be an issue with *some* particular tests run from a bash script.

**Comment by rossmuir** [comment]
For `safe_client` you should now run `cargo test` with ` --features "use-mock-routing"` on

**Comment by rossmuir** [comment]
same for `safe_vault` having a peek in the travis .yml files  for example : https://github.com/maidsafe/safe_vault/blob/master/.travis.yml files for each library should help keep up to date :-)

**Comment by theWebalyst** [comment]
Thanks Ross.

**Comment by rossmuir** [comment]
No worries :-)
