### ISSUE TITLE
Investigate security implications of using related public and private keys in `::sodiumoxide::crypto::box_::seal`

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe_client#171]
Currently [`Client::hybrid_encrypt`](https://github.com/maidsafe/safe_client/blob/94a7d501cebe11a517d66e67de039565b75be1ca/src/client/mod.rs#L273-L276) uses the MAID public and private encryption keys (an asymmetric key pair) to ultimately call [`::sodiumoxide::crypto::box_::seal(&asym_plain_text, asym_nonce, asym_public_key, asym_secret_key);`](https://github.com/maidsafe/safe_client/blob/94a7d501cebe11a517d66e67de039565b75be1ca/src/utility/mod.rs#L39).

I believe the intention of of the sodiumoxide function is that the public key is owned by the recipient of the encrypted message and is unrelated to the sender's private key.  Since we're using related keys here, it would be good to investigate whether this practice presents a security risk in the form of leaked information.

If it does, we should modify the utility function to assert that we've not passed related public and private keys.

**Comment by ustulation** [comment]
for reference:
http://crypto.stackexchange.com/questions/29314/using-related-pair-of-cryptographic-keys-to-open-seal-plaintext

**Comment by ustulation** [comment]
And also if it the case that `A` should be able to do both - encrypt and decrypt the message, will it not be better to use symmetric encryption alone ? We can store strong random Key and IV in Session Packet for this. Asymmetric would usually mean that `A` encrypts but no one (including `A`) can then decrypt that except `B`, the intended recipient; so unless we plan on sharing data that way we should always be using symmetric scheme ?

**Comment by Fraser999** [comment]
> will it not be better to use symmetric encryption alone ?

I would think so.  That's certainly how we did it before (using the parent ID and dir ID to create a symmetric encryption key and IV).

**Comment by ustulation** [comment]
Ok so just as an update .. i think it is clear from the answers in the post above that there is no security risk in what is being done right now. 

Quoting one of the answers for quick reference:
> The crypto_box function uses elliptic curve Diffie–Hellman on Curve25519. With a given input private key and public key it always generates the same symmetric key, which is then used for authenticated encryption. By using the private and public key from the same key pair you are generating the point a2G, which with a random a is just a random point on the curve. This point is then used to derive a symmetric key for authenticated encryption. Of course, it would be more efficient to just use that derived key (or a random key) in the first place, but as long as you keep the key pair secret, what you are doing is secure

Hence I am closing this with the solution that it is a non-issue. As for the corollary discussion i'm raising a new one where you can comment again (@Fraser999)
