### ISSUE TITLE
thread '<main>' panicked at 'Network IO Error'

### ISSUE THREAD

**Issue by a-jamesregan** [maidsafe/safe_client#93]
I've created a little safe networking using 3 vaults on a server and 5 or so vaults on my local machine, but when I try to run the <code>cargo run --example rest_api --features "USE_ACTUAL_ROUTING"</code> example, it fails.

	Auto Account Login
	==================

Trying to log into the created account using supplied credentials ...
trying to bootstrapped client
bootstrapped client
Sending connect request
received a ConnectResponse from Tcp(V4(192.168.2.110:32816))
Get sent out with message_id 489672644
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
Get sent out with message_id 489672645
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
trying to bootstrapped client
Account Login Successful !!

	-- Preparing storage ----

bootstrapped client
Sending connect request
Put sent out with message_id 1545089258
received a ConnectResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
Put sent out with message_id 1545089259
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
Put sent out with message_id 1545089260
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
Get sent out with message_id 1545089261
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
Put sent out with message_id 1545089262
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
Get sent out with message_id 1545089263
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a PutDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
Get sent out with message_id 1545089264
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
received a GetDataResponse from Tcp(V4(192.168.2.110:32816))
thread '<main>' panicked at 'Network IO Error', examples/rest_api.rs:323
Process didn't exit successfully: `target/debug/examples/rest_api` (exit code: 101)

**Comment by ustulation** [comment]
invalid as crates have changed .. rest-api moved to safe_nfs crate
